### ISSUE TITLE
WIN [ESC] = Word.doc

### ISSUE THREAD

**Issue by VirtualNomad19** [muckypaws/Manic-Miner-Engine#1]
not sure what you've embedded but i expect this wasn't intended:
<img width="400" alt="faoMM" src="https://user-images.githubusercontent.com/52613918/211198857-9741d21d-b158-4571-8b49-f64a8787e315.png">
https://forum.thegamecreators.com/thread/228873#msg2673031

**Comment by muckypaws** [comment]
Hello,

This is a fake letter activated under the 'BOSS Key' or Escape.

Back in the 80's when playing games on PC's during work time, people would get often get caught by their bosses, some games implemented the "Boss Key" which was a key combination to temporarily swap out the game screen with something like Lotus123 or Wordperfect Screens etc.

I've updated the idea, with something that looks like a letter you'd type in MS Word, so if the boss walks by when playing you hit escape, the game pauses and you can blag your way out of it.

It's a simple graphic that's overlaid found in 

media/images/BossKey.png

Which can be swapped out with an image of your choosing.

Nothing Nefarious, the letter if you read is my attempt at humour of Maria's Housekeeping services when Willy is left to clean his own mansion in JSW, the next conversion I'm working on...

Are you happy to close based on this explanation?

Kind Regards

**Comment by VirtualNomad19** [comment]
yes, thanks. tho i believe i found the actual establshment referenced in the "complaint" which you may want to change to an obviously ficticious one.

**Comment by muckypaws** [comment]
Thanks @VirtualNomad19 I'll make a revision for an update to make it more obvious.
